[sssd]
# Services = pam uniquement (pas nss) pour éviter les conflits de UID avec le compte local
services = pam
domains = ICSHUB.LOCAL
config_file_version = 2

[domain/ICSHUB.LOCAL]
id_provider = ldap
auth_provider = krb5
chpass_provider = krb5

# LDAP — pointe vers l'AD (192.168.30.50)
ldap_uri = ldap://192.168.30.50
ldap_search_base = DC=icshub,DC=local
ldap_schema = ad
ldap_id_mapping = true
ldap_referrals = false

# Bind pour les requêtes LDAP
ldap_default_bind_dn = CN=Administrator,CN=Users,DC=icshub,DC=local
ldap_default_authtok_type = password
ldap_default_authtok = Admin123!

# Recherche utilisateurs
ldap_user_search_base = CN=Users,DC=icshub,DC=local
ldap_user_object_class = user
ldap_user_name = sAMAccountName

# Kerberos
krb5_realm = ICSHUB.LOCAL
krb5_server = 192.168.30.50
krb5_kpasswd = 192.168.30.50

# Cache local si AD temporairement injoignable
cache_credentials = true
fallback_homedir = /home/%u
default_shell = /bin/bash
